CREATE TABLE USER_ROLES (
    id SERIAL PRIMARY KEY,
    "name" VARCHAR(20) NOT NULL,
    "description" VARCHAR(100)
);

CREATE TABLE USERS (
  id SERIAL PRIMARY KEY,
  firstname VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  user_role_id  INTEGER NOT NULL REFERENCES USER_ROLES (id),
  email VARCHAR(40) UNIQUE NOT NULL,
  crt_ts TIMESTAMP default CURRENT_TIMESTAMP,
  upd_ts  TIMESTAMP default CURRENT_TIMESTAMP,
  crt_userid INTEGER NOT NULL,
  upd_userid INTEGER NOT NULL
);

CREATE TABLE TYPES(
   id SERIAL PRIMARY KEY,
   "name" VARCHAR(100) NOT NULL,
   crt_ts TIMESTAMP default CURRENT_TIMESTAMP,
   upd_ts  TIMESTAMP default CURRENT_TIMESTAMP,
   crt_userid INTEGER NOT NULL REFERENCES USERS (id),
   upd_userid INTEGER NOT NULL REFERENCES USERS (id)
);

CREATE TABLE SUBTYPES(
   id SERIAL PRIMARY KEY,  
   "name" VARCHAR(100) NOT NULL,
   type_id INTEGER NOT NULL REFERENCES TYPES (id),
   crt_ts TIMESTAMP default CURRENT_TIMESTAMP,
   upd_ts  TIMESTAMP default CURRENT_TIMESTAMP,
   crt_userid INTEGER NOT NULL REFERENCES USERS (id),
   upd_userid INTEGER NOT NULL REFERENCES USERS (id)
);


CREATE TABLE EXPENSES (
    id SERIAL PRIMARY KEY,
    ts  TIMESTAMP NOT NULL,
    subtype_id INTEGER NOT NULL REFERENCES SUBTYPES (id),
    amount NUMERIC(100) NOT NULL,
    "description"  VARCHAR(1000) NOT NULL,
    crt_ts TIMESTAMP default CURRENT_TIMESTAMP,
    upd_ts  TIMESTAMP default CURRENT_TIMESTAMP,
    crt_userid INTEGER NOT NULL REFERENCES USERS (id),
    upd_userid INTEGER NOT NULL REFERENCES USERS (id)
);